/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check
         * @description Return API and engine health status.
         */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/picks/today": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Today Picks
         * @description Return Today's Top 20 ranked picks (BFF view model).
         */
        get: operations["today_picks_picks_today_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ranking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ranking
         * @description Return paginated full-universe ranking.
         */
        get: operations["ranking_ranking_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stock Meta
         * @description Return stock metadata for detail header.
         */
        get: operations["stock_meta_stock__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock/{code}/indicators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stock Indicators
         * @description Return OHLCV + indicator time series for charting.
         */
        get: operations["stock_indicators_stock__code__indicators_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock/{code}/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stock Domains
         * @description Return domain scores formatted for radar chart.
         */
        get: operations["stock_domains_stock__code__domains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stock/{code}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stock Rules
         * @description Return rule pass/fail and gate report for Explainable AI.
         */
        get: operations["stock_rules_stock__code__rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/backtest/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backtest Summary
         * @description Return aggregated backtest statistics from latest report.
         */
        get: operations["backtest_summary_backtest_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ws/market": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Market Sse
         * @description Server-Sent Events stream for market status (lightweight push).
         */
        get: operations["market_sse_ws_market_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BacktestRuleSummary
         * @description Aggregated metrics for one rule backtest.
         */
        BacktestRuleSummary: {
            /** Rule Id */
            rule_id: string;
            /** Symbol */
            symbol: string;
            /** Verdict */
            verdict: string;
            /** Total Return Pct */
            total_return_pct: number;
            /** Win Rate */
            win_rate: number;
            /** Max Drawdown Pct */
            max_drawdown_pct: number;
            /** Sharpe Ratio */
            sharpe_ratio: number;
            /** Trade Count */
            trade_count: number;
            /** Sample Days */
            sample_days: number;
        };
        /**
         * BacktestSummaryResponse
         * @description Overall backtest summary for UI table.
         */
        BacktestSummaryResponse: {
            /** Run Date */
            run_date?: string | null;
            /** Config Version */
            config_version?: string | null;
            /** Data Source */
            data_source?: string | null;
            /**
             * Rule Count
             * @default 0
             */
            rule_count: number;
            /**
             * Adopt Count
             * @default 0
             */
            adopt_count: number;
            /**
             * Reject Count
             * @default 0
             */
            reject_count: number;
            /** Rules */
            rules?: components["schemas"]["BacktestRuleSummary"][];
            /**
             * Available
             * @default false
             */
            available: boolean;
            /** Message */
            message?: string | null;
        };
        /**
         * DailyPicksResponse
         * @description Today's Top 20 picks response.
         */
        DailyPicksResponse: {
            /** Date */
            date: string;
            /** Mvp Mode */
            mvp_mode: boolean;
            /** Generated At */
            generated_at: string;
            /** Universe Size */
            universe_size: number;
            /** Candidates Evaluated */
            candidates_evaluated: number;
            /** Picks */
            picks: components["schemas"]["PickDetail"][];
        };
        /**
         * DomainScoreView
         * @description BFF view model for a single domain score (radar chart).
         */
        DomainScoreView: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Score */
            score: number;
            /** Max Score */
            max_score: number;
            /** Grade */
            grade?: string | null;
            /** State */
            state?: string | null;
            /**
             * Status
             * @default implemented
             */
            status: string;
        };
        /**
         * DomainsResponse
         * @description Domain scores formatted for radar chart.
         */
        DomainsResponse: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Domains */
            domains: components["schemas"]["DomainScoreView"][];
            /**
             * Radar
             * @description Normalized 0-100 scores keyed by domain label for ECharts radar
             */
            radar: {
                [key: string]: number;
            };
        };
        /**
         * GateReportItem
         * @description Gate evaluation row for Explainable AI.
         */
        GateReportItem: {
            /** Gate Key */
            gate_key?: string | null;
            /** Gate Name */
            gate_name?: string | null;
            /** Status */
            status: string;
            /** Threshold */
            threshold?: string | null;
            /** Actual */
            actual?: string | null;
            /** Reason */
            reason?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description System health check payload.
         */
        HealthResponse: {
            /**
             * Status
             * @example ok
             */
            status: string;
            /**
             * Service
             * @example tass-api
             */
            service: string;
            /** Engine Version */
            engine_version: string;
            /** Mvp Mode */
            mvp_mode: boolean;
            /** Picks Cached */
            picks_cached: boolean;
        };
        /**
         * IndicatorBar
         * @description Single OHLCV + indicator bar for charting.
         */
        IndicatorBar: {
            /** Date */
            date: string;
            /** Open */
            open: number;
            /** High */
            high: number;
            /** Low */
            low: number;
            /** Close */
            close: number;
            /** Volume */
            volume: number;
            /** Sma 20 */
            sma_20?: number | null;
            /** Sma 60 */
            sma_60?: number | null;
            /** Macd */
            macd?: number | null;
            /** Macd Signal */
            macd_signal?: number | null;
            /** Macd Hist */
            macd_hist?: number | null;
            /** Atr */
            atr?: number | null;
        };
        /**
         * IndicatorsResponse
         * @description Technical indicator time series (BFF chart view model).
         */
        IndicatorsResponse: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Bars */
            bars: components["schemas"]["IndicatorBar"][];
            /** Meta */
            meta?: {
                [key: string]: unknown;
            };
        };
        /**
         * PaginationMeta
         * @description Pagination metadata.
         */
        PaginationMeta: {
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
            /** Total Pages */
            total_pages: number;
        };
        /**
         * PickDetail
         * @description Full pick payload for stock detail / explainable AI.
         */
        PickDetail: {
            /** Rank */
            rank: number;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Total Score */
            total_score: number;
            /** Max Score */
            max_score: number;
            /** Domains */
            domains: {
                [key: string]: unknown;
            };
            /** Confidence */
            confidence?: number | null;
            /** Risk */
            risk?: number | null;
            /** Reasons */
            reasons?: string[];
            /** Gate */
            gate: string;
            /** Grade */
            grade?: string | null;
            /** Probability */
            probability?: number | null;
            /** Probability Grade */
            probability_grade?: string | null;
            /** Probability Level */
            probability_level?: string | null;
            /** Confidence Grade */
            confidence_grade?: string | null;
            /** Confidence Level */
            confidence_level?: string | null;
            /** Confidence Stars */
            confidence_stars?: string | null;
            /** Risk Grade */
            risk_grade?: string | null;
            /** Risk Grade Stars */
            risk_grade_stars?: string | null;
            /** Risk Level */
            risk_level?: string | null;
            /** Risk Decision */
            risk_decision?: string | null;
            /** Risk Breakdown */
            risk_breakdown?: {
                [key: string]: unknown;
            }[] | null;
            /** Recommendation */
            recommendation?: string | null;
            /** Recommendation Grade */
            recommendation_grade?: string | null;
            /** Recommendation Reason */
            recommendation_reason?: string[] | null;
            /** Passed Conditions */
            passed_conditions?: string[] | null;
            /** Failed Conditions */
            failed_conditions?: string[] | null;
            /** Gate Report */
            gate_report?: {
                [key: string]: unknown;
            }[] | null;
            /** Composite Breakdown */
            composite_breakdown?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * PickSummary
         * @description Compact pick card for lists.
         */
        PickSummary: {
            /** Rank */
            rank: number;
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Total Score */
            total_score: number;
            /** Max Score */
            max_score: number;
            /** Grade */
            grade?: string | null;
            /** Confidence */
            confidence?: number | null;
            /** Confidence Stars */
            confidence_stars?: string | null;
            /** Risk */
            risk?: number | null;
            /** Risk Level */
            risk_level?: string | null;
            /** Probability */
            probability?: number | null;
            /** Recommendation */
            recommendation?: string | null;
            /** Recommendation Grade */
            recommendation_grade?: string | null;
            /** Gate */
            gate: string;
        };
        /**
         * RankingResponse
         * @description Paginated full-universe ranking.
         */
        RankingResponse: {
            /** Date */
            date: string;
            /** Generated At */
            generated_at: string;
            pagination: components["schemas"]["PaginationMeta"];
            /** Items */
            items: components["schemas"]["PickSummary"][];
        };
        /**
         * RulesResponse
         * @description Rule pass/fail and gate deductions for Explainable AI.
         */
        RulesResponse: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Passed Conditions */
            passed_conditions?: string[];
            /** Failed Conditions */
            failed_conditions?: string[];
            /** Gate Report */
            gate_report?: components["schemas"]["GateReportItem"][];
            /** Composite Breakdown */
            composite_breakdown?: {
                [key: string]: unknown;
            };
            /** Recommendation Reason */
            recommendation_reason?: string[];
        };
        /**
         * StockMetaResponse
         * @description Stock metadata for detail header.
         */
        StockMetaResponse: {
            /** Symbol */
            symbol: string;
            /** Name */
            name: string;
            /** Market */
            market?: string | null;
            /** Rank */
            rank?: number | null;
            /** Total Score */
            total_score?: number | null;
            /** Max Score */
            max_score?: number | null;
            /** Grade */
            grade?: string | null;
            /** Recommendation */
            recommendation?: string | null;
            /** Gate */
            gate?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    today_picks_picks_today_get: {
        parameters: {
            query?: {
                /** @description Force regenerate picks from engine */
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DailyPicksResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ranking_ranking_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_meta_stock__code__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StockMetaResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_indicators_stock__code__indicators_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndicatorsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_domains_stock__code__domains_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stock_rules_stock__code__rules_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RulesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_summary_backtest_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BacktestSummaryResponse"];
                };
            };
        };
    };
    market_sse_ws_market_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
